# syntax=docker/dockerfile:1.7
# =============================================================================
# apps/api — FastAPI AI Orchestration API (spec §63 / §64).
#
# Build from the repository root:
#   docker build -f infra/docker/api.Dockerfile -t ai-coach/api:local .
#
# Three stages:
#   base    python + the *runtime* system libraries (kept minimal)
#   builder compilers + a self-contained /opt/venv built from pyproject.toml
#   runtime base + the copied venv + app source, running as an unprivileged user
#
# The venv-copy pattern matters here: asyncpg, pydantic-core, bcrypt and
# cryptography all pull a compiler toolchain, and that toolchain has no business
# being in a production image.
#
# infra/docker/worker.Dockerfile builds `FROM` the `runtime` stage of this file
# so the API and the async worker can never drift apart (§65 pipeline code is
# shared).
# =============================================================================

ARG PYTHON_VERSION=3.11

# -----------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim-bookworm AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Runtime-only system packages.
#   libpq5     — asyncpg does not need it, but psycopg-based alembic offline
#                tooling and `pg_isready`-style debugging do; it is 200 KB.
#   curl       — the container HEALTHCHECK and the compose readiness probe.
#   libmagic1  — content-type sniffing on upload, so a renamed .exe cannot pass
#                as a PDF (§40.1 file validation).
#   ca-certificates — outbound TLS to OpenAI / ElevenLabs / AUP (§70/§71/§72).
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      libpq5 \
      libmagic1 \
 && rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------------------------------
FROM base AS builder

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
 && rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH
RUN python -m venv "$VIRTUAL_ENV" \
 && pip install --upgrade pip setuptools wheel

WORKDIR /srv/api

# Dependency metadata only. Editing app code must not re-resolve the
# dependency graph.
# A COPY with several sources succeeds as long as at least one matches, so the
# `README*` glob is tolerant while `pyproject.toml` stays mandatory.
COPY apps/api/pyproject.toml apps/api/README* ./
# pyproject declares `readme = "README.md"`, which hatchling reads at build
# time. apps/api is owned by another team and its README may not have landed
# yet, so synthesise a stub rather than failing the image build on a doc file.
RUN [ -f README.md ] || printf '%s\n' \
      '# ai-coach-api' \
      '' \
      'Placeholder generated by infra/docker/api.Dockerfile because' \
      'apps/api/README.md was absent at build time.' > README.md

# `pip install .` (not `-e .`) so the venv is relocatable into the runtime
# stage. Dependencies are resolved from pyproject's [project.dependencies];
# apps/api owns that list.
RUN --mount=type=cache,target=/root/.cache/pip \
    mkdir -p app && touch app/__init__.py \
 && pip install --no-cache-dir .

# -----------------------------------------------------------------------------
FROM base AS runtime

ENV VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH \
    APP_ENV=production \
    PORT=8000 \
    UVICORN_WORKERS=2 \
    UVICORN_LOG_LEVEL=info \
    API_READY_PATH=/health/ready

# Unprivileged, no shell, no home-directory surprises. Fixed uid/gid so bind
# mounts and Kubernetes `runAsUser` line up.
RUN groupadd --gid 10001 app \
 && useradd --uid 10001 --gid app --create-home --shell /usr/sbin/nologin app

COPY --from=builder --chown=root:root /opt/venv /opt/venv

WORKDIR /srv/api
# alembic.ini is expected per docs/PROJECT_STRUCTURE.md (`database/migrations`),
# but it is owned by the API Platform team. Globbing keeps the image buildable
# while that tree fills in; `scripts/bootstrap.sh` reports a clear error
# if migrations cannot run.
COPY --chown=app:app apps/api/pyproject.toml apps/api/alembic.in* ./
COPY --chown=app:app apps/api/app ./app

# Somewhere for parser scratch files and OCR intermediates. Everything durable
# goes to S3/MinIO (§64); this directory is expendable.
RUN mkdir -p /srv/api/var && chown -R app:app /srv/api/var
ENV TMPDIR=/srv/api/var

USER app
EXPOSE 8000

# Readiness, not liveness: the route is expected to verify Postgres, Redis and
# Qdrant reachability before reporting healthy, which is what makes the
# `depends_on: condition: service_healthy` chain in docker-compose.yml mean
# something. Change API_READY_PATH if apps/api mounts it elsewhere.
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s --retries=4 \
  CMD curl -fsS "http://127.0.0.1:${PORT}${API_READY_PATH}" || exit 1

# Why uvicorn with --workers rather than gunicorn:
#   * FastAPI here is fully async; there is no blocking WSGI path that would
#     benefit from gunicorn's worker supervision.
#   * `--workers N` gives one process per core without a second supervisor
#     layer, and under Kubernetes you scale replicas instead (§49.3), so the
#     default stays low (2).
#   * --proxy-headers + --forwarded-allow-ips is required for correct client IPs
#     in the audit log (§42) behind the nginx proxy.
#   * --timeout-keep-alive is raised because the session WebSocket (§55) is
#     long-lived and must not be reaped between events.
#   * NO --reload here. That is `pnpm api:dev` on the host.
#
# Exec form, so uvicorn is PID 1 and receives SIGTERM for graceful drain.
CMD ["sh", "-c", "exec uvicorn app.main:app \
  --host 0.0.0.0 \
  --port ${PORT} \
  --workers ${UVICORN_WORKERS} \
  --log-level ${UVICORN_LOG_LEVEL} \
  --proxy-headers \
  --forwarded-allow-ips='*' \
  --timeout-keep-alive 75 \
  --timeout-graceful-shutdown 30 \
  --no-server-header"]
