# syntax=docker/dockerfile:1.7
# =============================================================================
# apps/api workers — async document and evaluation pipeline (spec §65, §26/§27).
#
# Build from the repository root:
#   docker build -f infra/docker/worker.Dockerfile -t ai-coach/worker:local .
#
# Same base as the API, on purpose
# --------------------------------
# The worker runs the same `app.rag.*` parser/chunker/embedder code and the same
# `app.domain.*` models as the request path. A version skew between the two
# would be nasty and silent: chunks the API cannot read back, or embeddings of a
# different dimension than the Qdrant collection expects. So both images:
#
#   * start from the identical `python:${PYTHON_VERSION}-slim-bookworm` base,
#   * resolve dependencies from the identical `apps/api/pyproject.toml`,
#   * build a relocatable /opt/venv in a throwaway builder stage.
#
# Docker cannot reference a stage defined in a *different* Dockerfile, so the
# base and builder stages below are deliberate structural twins of
# infra/docker/api.Dockerfile rather than an import. Only the OS package list
# and the entrypoint differ; the Python dependency closure has a single source
# of truth and therefore cannot drift.
#
# If you prefer a strict layer-sharing build (production registries), add to the
# `worker` service in docker-compose.yml:
#     build:
#       additional_contexts:
#         apibase: service:api
# and change the runtime `FROM` to `FROM apibase`. That requires Compose and
# loses the ability to `docker build` this file standalone, which is why it is
# not the default.
#
# What differs from the API image
# -------------------------------
#   + poppler-utils / tesseract-ocr  real document parsing and OCR (§65)
#   + language packs                 zh-Hant / zh-Hans / ja / en (§50 i18n)
#   - no exposed port                the worker pulls from Redis, never listens
# =============================================================================

# Keep in sync with infra/docker/api.Dockerfile.
ARG PYTHON_VERSION=3.11

# -----------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim-bookworm AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      libpq5 \
      libmagic1 \
 && rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------------------------------
FROM base AS builder

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
 && rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH
RUN python -m venv "$VIRTUAL_ENV" \
 && pip install --upgrade pip setuptools wheel

WORKDIR /srv/api

COPY apps/api/pyproject.toml apps/api/README* ./
RUN [ -f README.md ] || printf '%s\n' \
      '# ai-coach-api' \
      '' \
      'Placeholder generated by infra/docker/worker.Dockerfile.' > README.md

RUN --mount=type=cache,target=/root/.cache/pip \
    mkdir -p app && touch app/__init__.py \
 && pip install --no-cache-dir .

# -----------------------------------------------------------------------------
FROM base AS runtime

# ---------------------------------------------------------------------------
# Worker-only system packages. These are what make §65's "Parser → OCR if
# needed → Structure" step real rather than a stub, and they are exactly what
# we do NOT want inside the request-path image.
#   poppler-utils   PDF text extraction + page rasterisation feeding OCR
#   tesseract-ocr   scanned-PDF OCR, with the demo locale set (§50)
#   libgl1/libglib  runtime deps of the OpenCV-family layout detection used by
#                   table-aware chunking (ChunkStrategy 'table_aware')
# ---------------------------------------------------------------------------
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      poppler-utils \
      tesseract-ocr \
      tesseract-ocr-eng \
      tesseract-ocr-chi-tra \
      tesseract-ocr-chi-sim \
      tesseract-ocr-jpn \
      libgl1 \
      libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH \
    APP_ENV=production \
    CELERY_APP=app.workers.celery_app \
    CELERY_CONCURRENCY=2 \
    CELERY_QUEUES=documents,evaluation,maintenance \
    CELERY_LOGLEVEL=info \
    CELERY_MAX_TASKS_PER_CHILD=50 \
    TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata

# Same fixed uid/gid as the API image so a shared PVC or bind mount lines up.
RUN groupadd --gid 10001 app \
 && useradd --uid 10001 --gid app --create-home --shell /usr/sbin/nologin app

COPY --from=builder --chown=root:root /opt/venv /opt/venv

WORKDIR /srv/api
COPY --chown=app:app apps/api/pyproject.toml apps/api/alembic.in* ./
COPY --chown=app:app apps/api/app ./app

# Scratch space for page images and OCR intermediates. Nothing durable: the
# source document and every derived artefact belong in S3/MinIO (§64), and the
# `tmp/` prefix there has a 30-day expiry rule (see docker-compose.yml).
RUN mkdir -p /srv/api/var && chown -R app:app /srv/api/var
ENV TMPDIR=/srv/api/var

USER app

# Liveness is a control-bus ping rather than an HTTP probe. `-d celery@<host>`
# scopes it to *this* container, so a healthy sibling cannot mask a dead one.
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD celery -A "${CELERY_APP}" inspect ping -d "celery@$(hostname)" || exit 1

# Worker settings and the reasoning behind each:
#   --concurrency            prefork processes. Parsing and OCR are CPU-bound,
#                            so this tracks cores, not connections.
#   -Q documents,evaluation,maintenance
#                            explicit queues. Splitting them means a bulk PDF
#                            import cannot starve the end-of-session evaluation
#                            a trainee is waiting on (§29 → §26).
#   --max-tasks-per-child    recycles children to bound native-library leaks —
#                            a genuine problem with long-lived poppler and
#                            tesseract processes.
#   --prefetch-multiplier=1  tasks are long and unevenly sized; prefetching
#                            would pin a batch of large documents to one child.
#   --without-gossip/-mingle  removes inter-worker chatter we do not use and
#                            keeps the Redis broker quiet as replicas scale.
# Exec form via sh -c so the env vars expand; `exec` keeps celery as PID 1 and
# therefore able to finish the in-flight task on SIGTERM.
CMD ["sh", "-c", "exec celery -A ${CELERY_APP} worker \
  --loglevel=${CELERY_LOGLEVEL} \
  --concurrency=${CELERY_CONCURRENCY} \
  --queues=${CELERY_QUEUES} \
  --max-tasks-per-child=${CELERY_MAX_TASKS_PER_CHILD} \
  --prefetch-multiplier=1 \
  --without-gossip \
  --without-mingle"]
