'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { Question, QuestionType } from '@ai-coach/shared';
import { AlertTriangle, Check, Save, Sparkles, X } from 'lucide-react';
import { Button, Field, GlassCard, Input, Pill, Select, Textarea } from '@/components/ui';
import { PageHeader } from '@/components/app-shell';
import { ContentStatusPill, DifficultyPill } from '@/components/status';
import { CitationList } from '@/components/transcript';
import { MOCK_QUESTIONS, QUESTION_TYPE_LABEL, questionById } from '@/lib/fixtures/questions';
import { MOCK_KNOWLEDGE_BASES } from '@/lib/fixtures/knowledge';
import { SKILL_LABEL } from '@/lib/fixtures/evaluations';
import { SCOPE } from '@/lib/fixtures/constants';
import { useCan } from '@/lib/auth-context';
import { formatRelative } from '@/lib/utils';

const EMPTY: Question = {
  id: 'new',
  ...SCOPE,
  title: '',
  type: 'multiple_choice',
  prompt: '',
  difficulty: 'medium',
  required_keywords: [],
  forbidden_claims: [],
  compliance_rules: [],
  tags: [],
  version: 1,
  status: 'draft',
  created_at: new Date(0).toISOString(),
  updated_at: new Date(0).toISOString(),
};

/**
 * §58-22 Question Editor, with the §15 / §38 **review-before-publish gate**.
 *
 * A `generated` or `review_required` question shows the review bar at the top:
 * it cannot be assigned until a reviewer approves it, and the sources it was
 * generated from are always visible next to the prompt.
 */
export function QuestionEditorPage({ questionId, reviewMode }: { questionId: string; reviewMode?: boolean }) {
  const canEdit = useCan('question.manage');
  const canPublish = useCan('content.publish');
  const isNew = questionId === 'new';

  const source = useMemo(() => (isNew ? EMPTY : questionById(questionId) ?? EMPTY), [isNew, questionId]);
  const [draft, setDraft] = useState<Question>(source);
  const [decision, setDecision] = useState<'pending' | 'approved' | 'rejected'>('pending');

  // `reviewMode` comes from ?review=1 (the "Review" action in the bank), which
  // surfaces the gate even for an item whose status has already moved on.
  const needsReview = Boolean(reviewMode) || ['generated', 'review_required'].includes(draft.status);

  const list = (values: string[]) => values.join('\n');
  const parseList = (value: string) => value.split('\n').map((line) => line.trim()).filter(Boolean);

  return (
    <div className="space-y-5 pb-4">
      <PageHeader
        breadcrumbs={[
          { label: 'Question Bank', href: '/questions' },
          { label: isNew ? 'New question' : draft.title || 'Question' },
        ]}
        title={isNew ? 'New question' : draft.title || 'Question editor'}
        description={QUESTION_TYPE_LABEL[draft.type]}
        meta={
          <>
            <ContentStatusPill status={draft.status} />
            <DifficultyPill difficulty={draft.difficulty} />
            <Pill tone="neutral" size="sm">v{draft.version}</Pill>
            {draft.generated_by_model ? (
              <Pill tone="gradient" size="sm">
                <Sparkles size={11} strokeWidth={2} aria-hidden />
                {draft.generated_by_model}
              </Pill>
            ) : null}
          </>
        }
        actions={
          <>
            <Button variant="secondary" size="sm" disabled={!canEdit}>
              <Save size={15} strokeWidth={1.8} aria-hidden />
              Save
            </Button>
            <Button variant="primary" size="sm" disabled={!canPublish || needsReview}>
              Publish
            </Button>
          </>
        }
      />

      {/* Review gate (§15 / §38) */}
      {needsReview ? (
        <GlassCard tone="strong" className="p-5">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div className="flex items-start gap-3">
              <AlertTriangle size={18} strokeWidth={1.8} aria-hidden className="mt-0.5 text-state-warning" />
              <div>
                <h2 className="text-card-title">Human review required before publish</h2>
                <p className="mt-1 max-w-2xl text-body-sm text-text-secondary">
                  {draft.generated_by_model
                    ? `Generated by ${draft.generated_by_model}. Check the claim against the cited chunks, confirm the correct answer, and confirm no forbidden claim is implied.`
                    : 'This item was flagged for review. It cannot be assigned until a reviewer approves it.'}
                </p>
                {decision !== 'pending' ? (
                  <p className="mt-2 text-body-sm">
                    <Pill tone={decision === 'approved' ? 'success' : 'danger'} size="sm">
                      {decision === 'approved' ? 'Approved in this session' : 'Rejected in this session'}
                    </Pill>
                  </p>
                ) : null}
              </div>
            </div>

            {canPublish ? (
              <div className="flex shrink-0 gap-2">
                <Button variant="ghost" size="sm" onClick={() => setDecision('rejected')}>
                  <X size={15} strokeWidth={2} aria-hidden />
                  Reject
                </Button>
                <Button variant="primary" size="sm" onClick={() => setDecision('approved')}>
                  <Check size={15} strokeWidth={2} aria-hidden />
                  Approve
                </Button>
              </div>
            ) : (
              <p className="text-body-sm text-text-tertiary">Your role cannot approve content.</p>
            )}
          </div>
        </GlassCard>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]">
        <div className="space-y-4">
          <GlassCard className="space-y-4 p-5">
            <h2 className="text-card-title">Question</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Title" hint="Internal label used in lists and reports.">
                <Input
                  value={draft.title}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setDraft({ ...draft, title: e.target.value })}
                />
              </Field>
              <Field label="Type">
                <Select
                  value={draft.type}
                  onValueChange={(value: string) => setDraft({ ...draft, type: value as QuestionType })}
                  options={(Object.keys(QUESTION_TYPE_LABEL) as QuestionType[]).map((type) => ({
                    value: type,
                    label: QUESTION_TYPE_LABEL[type],
                  }))}
                />
              </Field>
              <Field label="Difficulty">
                <Select
                  value={draft.difficulty}
                  onValueChange={(value: string) => setDraft({ ...draft, difficulty: value as Question['difficulty'] })}
                  options={[
                    { value: 'easy', label: 'Easy' },
                    { value: 'medium', label: 'Medium' },
                    { value: 'hard', label: 'Hard' },
                    { value: 'expert', label: 'Expert' },
                  ]}
                />
              </Field>
              <Field label="Knowledge base">
                <Select
                  value={draft.knowledge_base_id ?? ''}
                  onValueChange={(value: string) => setDraft({ ...draft, knowledge_base_id: value || undefined })}
                  options={[
                    { value: '', label: 'Not grounded' },
                    ...MOCK_KNOWLEDGE_BASES.map((kb) => ({ value: kb.id, label: kb.name })),
                  ]}
                />
              </Field>
              <Field label="Category">
                <Input
                  value={draft.category ?? ''}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setDraft({ ...draft, category: e.target.value })}
                />
              </Field>
              <Field label="Skill dimension">
                <Select
                  value={draft.skill ?? ''}
                  onValueChange={(value: string) =>
                    setDraft({ ...draft, skill: (value || undefined) as Question['skill'] })
                  }
                  options={[
                    { value: '', label: 'Not mapped' },
                    ...Object.entries(SKILL_LABEL).map(([key, label]) => ({ value: key, label })),
                  ]}
                />
              </Field>
            </div>

            <Field label="Prompt" hint="What the trainee reads or hears.">
              <Textarea
                rows={4}
                value={draft.prompt}
                disabled={!canEdit}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDraft({ ...draft, prompt: e.target.value })}
              />
            </Field>

            {['multiple_choice', 'true_false', 'short_answer'].includes(draft.type) ? (
              <Field label="Correct answer">
                <Input
                  value={draft.correct_answer ?? ''}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setDraft({ ...draft, correct_answer: e.target.value })}
                />
              </Field>
            ) : (
              <Field label="Rubric" hint="How an open answer is judged. Required for open-ended and role-play items.">
                <Textarea
                  rows={3}
                  value={draft.rubric ?? ''}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDraft({ ...draft, rubric: e.target.value })}
                />
              </Field>
            )}

            <Field label="Explanation" hint="Shown after the answer is submitted.">
              <Textarea
                rows={3}
                value={draft.explanation ?? ''}
                disabled={!canEdit}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDraft({ ...draft, explanation: e.target.value })}
              />
            </Field>
          </GlassCard>

          <GlassCard className="space-y-4 p-5">
            <h2 className="text-card-title">Scoring guards</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Required keywords" hint="One per line.">
                <Textarea
                  rows={4}
                  value={list(draft.required_keywords)}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                    setDraft({ ...draft, required_keywords: parseList(e.target.value) })
                  }
                />
              </Field>
              <Field label="Forbidden claims" hint="One per line. Using these fails the item outright.">
                <Textarea
                  rows={4}
                  value={list(draft.forbidden_claims)}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                    setDraft({ ...draft, forbidden_claims: parseList(e.target.value) })
                  }
                />
              </Field>
              <Field label="Compliance rules" hint="Policy identifiers, one per line.">
                <Textarea
                  rows={3}
                  value={list(draft.compliance_rules)}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                    setDraft({ ...draft, compliance_rules: parseList(e.target.value) })
                  }
                />
              </Field>
              <Field label="Tags" hint="One per line.">
                <Textarea
                  rows={3}
                  value={list(draft.tags)}
                  disabled={!canEdit}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                    setDraft({ ...draft, tags: parseList(e.target.value) })
                  }
                />
              </Field>
            </div>
          </GlassCard>
        </div>

        <div className="space-y-4">
          {draft.citations && draft.citations.length > 0 ? (
            <GlassCard tone="strong" className="p-5">
              <h2 className="text-card-title">Source citations</h2>
              <p className="mt-1 text-body-sm text-text-secondary">
                Every AI-generated item carries the chunks it was derived from. Verify the claim against
                these before approving.
              </p>
              <CitationList className="mt-3" citations={draft.citations} />
            </GlassCard>
          ) : null}

          <GlassCard className="p-5">
            <h2 className="text-card-title">Preview</h2>
            <div className="mt-3 rounded-card-sm border border-border-soft bg-glass-card p-4">
              <p className="text-tiny uppercase text-text-tertiary">
                {QUESTION_TYPE_LABEL[draft.type]} · {draft.difficulty}
              </p>
              <p className="mt-2 whitespace-pre-wrap text-body">
                {draft.prompt || 'The prompt will appear here.'}
              </p>
              {draft.type === 'true_false' ? (
                <div className="mt-3 flex gap-2">
                  <Pill tone="neutral" size="sm">True</Pill>
                  <Pill tone="neutral" size="sm">False</Pill>
                </div>
              ) : null}
              {draft.type === 'voice_response' ? (
                <p className="mt-3 text-tiny text-text-tertiary">Answered by voice · 60 second limit</p>
              ) : null}
            </div>
          </GlassCard>

          <GlassCard className="p-5">
            <h2 className="text-card-title">History</h2>
            <ul className="mt-3 space-y-2 text-body-sm">
              <li className="flex items-center justify-between gap-3">
                <span className="text-text-tertiary">Created</span>
                <span>{isNew ? 'Not saved yet' : formatRelative(draft.created_at)}</span>
              </li>
              <li className="flex items-center justify-between gap-3">
                <span className="text-text-tertiary">Updated</span>
                <span>{isNew ? '—' : formatRelative(draft.updated_at)}</span>
              </li>
              <li className="flex items-center justify-between gap-3">
                <span className="text-text-tertiary">Reviewer</span>
                <span>{draft.reviewer_id ?? 'Not reviewed'}</span>
              </li>
            </ul>
            <p className="mt-4 text-tiny text-text-tertiary">
              Every edit bumps the version and is recorded in the audit log.
            </p>
          </GlassCard>

          <p className="text-tiny text-text-tertiary">
            {MOCK_QUESTIONS.length} questions in this workspace ·{' '}
            <Link href="/questions" className="text-accent-indigo hover:underline">
              back to the bank
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
