"""Pydantic v2 mirror of ``packages/shared`` (spec §53–§56).

Field names and enum literal values are byte-identical to the TypeScript contract.
Any change here MUST be made in ``packages/shared/src/*.ts`` in the same commit.

This package re-exports the whole contract surface so consumers can write
``from app.domain import PersonaSimulationState`` without knowing which cluster module
a model lives in. The per-cluster modules remain the canonical definition sites:

=========================  ==================================================
Module                     Mirrors
=========================  ==================================================
``enums``                  ``state-machines.ts`` + every string union
``common``                 ``ID`` / ``ISODateTime`` / ``TenantScoped`` + paging
``persona``                ``persona.ts`` + ``Persona`` / ``PersonaVoiceConfig``
``knowledge``              KnowledgeBase / Document / Chunk / Citation
``question``               Question / QuestionVersion
``scenario``               Scenario / Rubric / Assignment
``session``                TrainingSession / TranscriptTurn / CoachInsight
``evaluation``             Evaluation / SkillScore / ComplianceFinding
``events``                 ``events.ts`` — ``StreamingEvent`` / ``ClientCommand``
``runtime``                ``runtime.ts`` — capability + policy
``audit``                  ``AuditEvent`` + the §42 action list
``analytics``              SkillProfile / Recommendation / team aggregates
``request_response``       API-only request/response DTOs
=========================  ==================================================
"""

from app.domain.analytics import (
    AnalyticsFilter,
    KnowledgeMaterialSuggestion,
    Recommendation,
    Report,
    ReportExport,
    SkillMatrixCell,
    SkillProfile,
    TeamAnalytics,
    TeamMemberSummary,
)
from app.domain.audit import AuditAction, AuditEvent, AuditQuery
from app.domain.common import (
    ID,
    Acknowledgement,
    Confidence,
    DomainModel,
    ISODateTime,
    Organization,
    OrganizationScoped,
    Page,
    PageParams,
    Score100,
    Team,
    TenantScoped,
    User,
    Workspace,
)
from app.domain.enums import (
    AGENT_NAMES,
    SKILL_KEYS,
    AgentName,
    AuditResult,
    ChunkStrategy,
    CoachInsightKind,
    ComplianceFindingType,
    ComplianceRisk,
    ComputeBackend,
    ContentStatus,
    Difficulty,
    DocumentSourceKind,
    DocumentState,
    ExportFormat,
    FallbackTarget,
    IntegrationKind,
    IntegrationStatus,
    KnowledgeAclScope,
    KnowledgePermission,
    LocalTask,
    MemoryClass,
    PersonaEmotion,
    QuestionType,
    ReportKind,
    ReviewerStatus,
    Role,
    RuntimeState,
    ScenarioPhase,
    SessionMode,
    SessionState,
    SkillKey,
    SpeakerKind,
    SpeechSpeaker,
    VoiceProvider,
    WebGpuMode,
    WorkspaceKind,
)
from app.domain.evaluation import (
    ComplianceFinding,
    Evaluation,
    EvaluationEvidence,
    HumanOverride,
    SkillScore,
)
from app.domain.events import (
    CLIENT_COMMAND_ADAPTER,
    CLIENT_COMMAND_TYPES,
    STREAMING_EVENT_ADAPTER,
    STREAMING_EVENT_TYPES,
    AckCommand,
    AgentResponseFinalEvent,
    AgentResponsePartialEvent,
    AgentThinkingEvent,
    ClientCommand,
    ClientIntentHintCommand,
    CoachInsightEvent,
    CoachRequestHintCommand,
    ComplianceWarningEvent,
    ConnectionReconnectingEvent,
    EventBase,
    KnowledgeCitationEvent,
    MessageSendCommand,
    PersonaStateUpdatedEvent,
    RuntimeFallbackEvent,
    ScoreUpdatedEvent,
    SessionCompletedEvent,
    SessionEndCommand,
    SessionErrorEvent,
    SessionPauseCommand,
    SessionPausedEvent,
    SessionResumeCommand,
    SessionResumedEvent,
    SessionStartedEvent,
    SpeechFinalEvent,
    SpeechPartialEvent,
    SpeechStartedEvent,
    StreamingEvent,
    VoicePushToTalkCommand,
    dump_event,
    dump_event_json,
    parse_client_command,
    parse_event,
)
from app.domain.knowledge import (
    Chunk,
    Citation,
    DocumentVersion,
    EmbeddingIndex,
    KnowledgeAcl,
    KnowledgeBase,
    KnowledgeDocument,
)
from app.domain.persona import (
    Persona,
    PersonaHiddenState,
    PersonaSimulationState,
    PersonaSimulationStateDelta,
    PersonaStateEvent,
    PersonaTraits,
    PersonaVoiceConfig,
)
from app.domain.question import Question, QuestionVersion
from app.domain.runtime import (
    AdapterInfo,
    ComputeCapability,
    LocalModelFile,
    LocalModelManifest,
    RuntimePolicy,
    RuntimeTelemetry,
)
from app.domain.scenario import (
    Assignment,
    CustomSkill,
    Rubric,
    Scenario,
    ScenarioVersion,
)
from app.domain.session import (
    CoachInsight,
    LiveScore,
    ScoreEvent,
    TrainingSession,
    TranscriptTurn,
)

__all__ = [
    "AGENT_NAMES",
    "CLIENT_COMMAND_ADAPTER",
    "CLIENT_COMMAND_TYPES",
    "ID",
    "SKILL_KEYS",
    "STREAMING_EVENT_ADAPTER",
    "STREAMING_EVENT_TYPES",
    "AckCommand",
    "Acknowledgement",
    "AdapterInfo",
    "AgentName",
    "AgentResponseFinalEvent",
    "AgentResponsePartialEvent",
    "AgentThinkingEvent",
    "AnalyticsFilter",
    "Assignment",
    "AuditAction",
    "AuditEvent",
    "AuditQuery",
    "AuditResult",
    "Chunk",
    "ChunkStrategy",
    "Citation",
    "ClientCommand",
    "ClientIntentHintCommand",
    "CoachInsight",
    "CoachInsightEvent",
    "CoachInsightKind",
    "CoachRequestHintCommand",
    "ComplianceFinding",
    "ComplianceFindingType",
    "ComplianceRisk",
    "ComplianceWarningEvent",
    "ComputeBackend",
    "ComputeCapability",
    "Confidence",
    "ConnectionReconnectingEvent",
    "ContentStatus",
    "CustomSkill",
    "Difficulty",
    "DocumentSourceKind",
    "DocumentState",
    "DocumentVersion",
    "DomainModel",
    "EmbeddingIndex",
    "Evaluation",
    "EvaluationEvidence",
    "EventBase",
    "ExportFormat",
    "FallbackTarget",
    "HumanOverride",
    "ISODateTime",
    "IntegrationKind",
    "IntegrationStatus",
    "KnowledgeAcl",
    "KnowledgeAclScope",
    "KnowledgeBase",
    "KnowledgeCitationEvent",
    "KnowledgeDocument",
    "KnowledgeMaterialSuggestion",
    "KnowledgePermission",
    "LiveScore",
    "LocalModelFile",
    "LocalModelManifest",
    "LocalTask",
    "MemoryClass",
    "MessageSendCommand",
    "Organization",
    "OrganizationScoped",
    "Page",
    "PageParams",
    "Persona",
    "PersonaEmotion",
    "PersonaHiddenState",
    "PersonaSimulationState",
    "PersonaSimulationStateDelta",
    "PersonaStateEvent",
    "PersonaStateUpdatedEvent",
    "PersonaTraits",
    "PersonaVoiceConfig",
    "Question",
    "QuestionType",
    "QuestionVersion",
    "Recommendation",
    "Report",
    "ReportExport",
    "ReportKind",
    "ReviewerStatus",
    "Role",
    "Rubric",
    "RuntimeFallbackEvent",
    "RuntimePolicy",
    "RuntimeState",
    "RuntimeTelemetry",
    "Scenario",
    "ScenarioPhase",
    "ScenarioVersion",
    "Score100",
    "ScoreEvent",
    "ScoreUpdatedEvent",
    "SessionCompletedEvent",
    "SessionEndCommand",
    "SessionErrorEvent",
    "SessionMode",
    "SessionPauseCommand",
    "SessionPausedEvent",
    "SessionResumeCommand",
    "SessionResumedEvent",
    "SessionStartedEvent",
    "SessionState",
    "SkillKey",
    "SkillMatrixCell",
    "SkillProfile",
    "SkillScore",
    "SpeakerKind",
    "SpeechFinalEvent",
    "SpeechPartialEvent",
    "SpeechSpeaker",
    "SpeechStartedEvent",
    "StreamingEvent",
    "Team",
    "TeamAnalytics",
    "TeamMemberSummary",
    "TenantScoped",
    "TrainingSession",
    "TranscriptTurn",
    "User",
    "VoiceProvider",
    "VoicePushToTalkCommand",
    "WebGpuMode",
    "Workspace",
    "WorkspaceKind",
    "dump_event",
    "dump_event_json",
    "parse_client_command",
    "parse_event",
]
